version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      MYSQL_DATABASE: cloud-computing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    networks:
      - cloud-computing
  www:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    networks:
      - cloud-computing
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - cloud-computing
  nginx:
    image: fsouza/docker-ssl-proxy
    restart: always
    ports:
      - 443:443
    environment:
      DOMAIN: ec2-174-129-60-181.compute-1.amazonaws.com
      TARGET_PORT: 80
      TARGET_HOST: www
      SSL_PORT: 443
    volumes:
      - "./certs"
    networks:
      - cloud-computing
networks:
  cloud-computing:
    driver: bridge